# 2. Installing TensorFlow

In [5]:
import tensorflow as tf

hello_constant = tf.constant('Hello World!')

with tf.Session() as sess:
    output = sess.run(hello_constant)
    print(type(output), output)

<class 'bytes'> b'Hello World!'


# 4. Quiz: TensorFlow Input

In [6]:
# Solution is available in the other "solution.py" tab
import tensorflow as tf

def run():
    output = None
    x = tf.placeholder(tf.int32)

    with tf.Session() as sess:
        # TODO: Feed the x tensor 123
        output = sess.run(x, feed_dict={x: 123})
        print(type(output), output)
    return output

run()


<class 'numpy.ndarray'> 123


array(123, dtype=int32)

# 5. TensorFlow Math

In [29]:
# Solution is available in the other "solution.py" tab
import tensorflow as tf

# TODO: Convert the following to TensorFlow:
# x = 10
# y = 2
# z = x/y - 1

x = tf.constant(10)
y = tf.constant(2)

# z = tf.add(x, y)
# z = tf.divide(x, y) - 1
z = tf.subtract(tf.divide(x, y), tf.cast(tf.constant(1), tf.float64))

# TODO: Print z from a session
with tf.Session() as sess:
    output = sess.run(z)
    print(type(output), output)

<class 'numpy.float64'> 4.0


## solution.py

In [ ]:
# Quiz Solution
# Note: You can't run code in this tab
import tensorflow as tf

# TODO: Convert the following to TensorFlow:
x = tf.constant(10)
y = tf.constant(2)
z = tf.subtract(tf.divide(x,y),tf.cast(tf.constant(1), tf.float64))

# TODO: Print z from a session
with tf.Session() as sess:
    output = sess.run(z)
    print(output)


# 9. Quiz: Mini-batch

In [32]:
55000 * 784 * 4, 55000 * 10 * 4, 784 * 10 * 4, 10 * 4

(172480000, 2200000, 31360, 40)

In [35]:
50000 / 128

390.625

In [37]:
50000 % 128

80

## Test Mini-batch Function

### quiz.py

In [42]:
import math
def batches(batch_size, features, labels):
    """
    Create batches of features and labels
    :param batch_size: The batch size
    :param features: List of features
    :param labels: List of labels
    :return: Batches of (Features, Labels)
    """
    assert len(features) == len(labels)

    # TODO: Implement batching
    batch_count = math.ceil(len(features) / batch_size)    
    batch_lst = []
    for i in range(batch_count):        
        start_ind = i * batch_size
        end_ind = (i + 1) * batch_size

        batch = []
        batch.append(features[start_ind : end_ind])
        batch.append(labels[start_ind : end_ind])
        
        batch_lst.append(batch)
        
    return batch_lst

### sandbox.py

In [43]:
# from quiz import batches
from pprint import pprint

# 4 Samples of features
example_features = [
    ['F11','F12','F13','F14'],
    ['F21','F22','F23','F24'],
    ['F31','F32','F33','F34'],
    ['F41','F42','F43','F44']]
# 4 Samples of labels
example_labels = [
    ['L11','L12'],
    ['L21','L22'],
    ['L31','L32'],
    ['L41','L42']]

# PPrint prints data structures like 2d arrays, so they are easier to read
pprint(batches(3, example_features, example_labels))


[[[['F11', 'F12', 'F13', 'F14'],
   ['F21', 'F22', 'F23', 'F24'],
   ['F31', 'F32', 'F33', 'F34']],
  [['L11', 'L12'], ['L21', 'L22'], ['L31', 'L32']]],
 [[['F41', 'F42', 'F43', 'F44']], [['L41', 'L42']]]]


### quiz_solution.py

In [44]:
import math
def batches(batch_size, features, labels):
    """
    Create batches of features and labels
    :param batch_size: The batch size
    :param features: List of features
    :param labels: List of labels
    :return: Batches of (Features, Labels)
    """
    assert len(features) == len(labels)
    # TODO: Implement batching
    output_batches = []
    
    sample_size = len(features)
    for start_i in range(0, sample_size, batch_size):
        end_i = start_i + batch_size
        batch = [features[start_i:end_i], labels[start_i:end_i]]
        output_batches.append(batch)
        
    return output_batches


## Run Model with Mini-batch

### helper.py

In [46]:
import math
def batches(batch_size, features, labels):
    """
    Create batches of features and labels
    :param batch_size: The batch size
    :param features: List of features
    :param labels: List of labels
    :return: Batches of (Features, Labels)
    """
    assert len(features) == len(labels)
    outout_batches = []
    
    sample_size = len(features)
    for start_i in range(0, sample_size, batch_size):
        end_i = start_i + batch_size
        batch = [features[start_i:end_i], labels[start_i:end_i]]
        outout_batches.append(batch)
        
    return outout_batches


### quiz.py

In [49]:
from tensorflow.examples.tutorials.mnist import input_data
import tensorflow as tf
import numpy as np
# from helper import batches

learning_rate = 0.001
n_input = 784  # MNIST data input (img shape: 28*28)
n_classes = 10  # MNIST total classes (0-9 digits)

# Import MNIST data
mnist = input_data.read_data_sets('/datasets/ud730/mnist', one_hot=True)

# The features are already scaled and the data is shuffled
train_features = mnist.train.images
test_features = mnist.test.images

train_labels = mnist.train.labels.astype(np.float32)
test_labels = mnist.test.labels.astype(np.float32)

# Features and Labels
features = tf.placeholder(tf.float32, [None, n_input])
labels = tf.placeholder(tf.float32, [None, n_classes])

# Weights & bias
weights = tf.Variable(tf.random_normal([n_input, n_classes]))
bias = tf.Variable(tf.random_normal([n_classes]))

# Logits - xW + b
logits = tf.add(tf.matmul(features, weights), bias)

# Define loss and optimizer
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=labels))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

# Calculate accuracy
correct_prediction = tf.equal(tf.argmax(logits, 1), tf.argmax(labels, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

# TODO: Set batch size
batch_size = 128
assert batch_size is not None, 'You must set the batch size'

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    
    # TODO: Train optimizer on all batches
    for batch_features, batch_labels in batches(batch_size, train_features, train_labels):
        _, batch_accuracy = sess.run([optimizer, accuracy], feed_dict={features: batch_features, labels: batch_labels})
        print('batch_accuracy', batch_accuracy)

    # Calculate accuracy for test dataset
    test_accuracy = sess.run(
        accuracy,
        feed_dict={features: test_features, labels: test_labels})

print('Test Accuracy: {}'.format(test_accuracy))


Extracting /datasets/ud730/mnist/train-images-idx3-ubyte.gz
Extracting /datasets/ud730/mnist/train-labels-idx1-ubyte.gz
Extracting /datasets/ud730/mnist/t10k-images-idx3-ubyte.gz
Extracting /datasets/ud730/mnist/t10k-labels-idx1-ubyte.gz
batch_accuracy 0.179688
batch_accuracy 0.117188
batch_accuracy 0.117188
batch_accuracy 0.101562
batch_accuracy 0.132812
batch_accuracy 0.203125
batch_accuracy 0.171875
batch_accuracy 0.164062
batch_accuracy 0.164062
batch_accuracy 0.203125
batch_accuracy 0.148438
batch_accuracy 0.1875
batch_accuracy 0.195312
batch_accuracy 0.15625
batch_accuracy 0.125
batch_accuracy 0.132812
batch_accuracy 0.078125
batch_accuracy 0.148438
batch_accuracy 0.0859375
batch_accuracy 0.179688
batch_accuracy 0.117188
batch_accuracy 0.09375
batch_accuracy 0.101562
batch_accuracy 0.164062
batch_accuracy 0.148438
batch_accuracy 0.0859375
batch_accuracy 0.140625
batch_accuracy 0.132812
batch_accuracy 0.171875
batch_accuracy 0.109375
batch_accuracy 0.101562
batch_accuracy 0.1875
b

batch_accuracy 0.171875
batch_accuracy 0.0859375
batch_accuracy 0.171875
batch_accuracy 0.179688
batch_accuracy 0.132812
batch_accuracy 0.203125
batch_accuracy 0.113636
Test Accuracy: 0.13650000095367432


# 10. Epochs

In [51]:
from tensorflow.examples.tutorials.mnist import input_data
import tensorflow as tf
import numpy as np
# from helper import batches  # Helper function created in Mini-batching section


def print_epoch_stats(epoch_i, sess, last_features, last_labels):
    """
    Print cost and validation accuracy of an epoch
    """
    current_cost = sess.run(
        cost,
        feed_dict={features: last_features, labels: last_labels})
    valid_accuracy = sess.run(
        accuracy,
        feed_dict={features: valid_features, labels: valid_labels})
    print('Epoch: {:<4} - Cost: {:<8.3} Valid Accuracy: {:<5.3}'.format(
        epoch_i,
        current_cost,
        valid_accuracy))

n_input = 784  # MNIST data input (img shape: 28*28)
n_classes = 10  # MNIST total classes (0-9 digits)

# Import MNIST data
mnist = input_data.read_data_sets('/datasets/ud730/mnist', one_hot=True)

# The features are already scaled and the data is shuffled
train_features = mnist.train.images
valid_features = mnist.validation.images
test_features = mnist.test.images

train_labels = mnist.train.labels.astype(np.float32)
valid_labels = mnist.validation.labels.astype(np.float32)
test_labels = mnist.test.labels.astype(np.float32)

# Features and Labels
features = tf.placeholder(tf.float32, [None, n_input])
labels = tf.placeholder(tf.float32, [None, n_classes])

# Weights & bias
weights = tf.Variable(tf.random_normal([n_input, n_classes]))
bias = tf.Variable(tf.random_normal([n_classes]))

# Logits - xW + b
logits = tf.add(tf.matmul(features, weights), bias)

# Define loss and optimizer
learning_rate = tf.placeholder(tf.float32)
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=labels))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

# Calculate accuracy
correct_prediction = tf.equal(tf.argmax(logits, 1), tf.argmax(labels, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

init = tf.global_variables_initializer()

batch_size = 128
epochs = 100
learn_rate = 0.001

train_batches = batches(batch_size, train_features, train_labels)

with tf.Session() as sess:
    sess.run(init)

    # Training cycle
    for epoch_i in range(epochs):

        # Loop over all batches
        for batch_features, batch_labels in train_batches:
            train_feed_dict = {
                features: batch_features,
                labels: batch_labels,
                learning_rate: learn_rate}
            sess.run(optimizer, feed_dict=train_feed_dict)

        # Print cost and validation accuracy of an epoch
        print_epoch_stats(epoch_i, sess, batch_features, batch_labels)

    # Calculate accuracy for test dataset
    test_accuracy = sess.run(
        accuracy,
        feed_dict={features: test_features, labels: test_labels})

print('Test Accuracy: {}'.format(test_accuracy))

Extracting /datasets/ud730/mnist/train-images-idx3-ubyte.gz
Extracting /datasets/ud730/mnist/train-labels-idx1-ubyte.gz
Extracting /datasets/ud730/mnist/t10k-images-idx3-ubyte.gz
Extracting /datasets/ud730/mnist/t10k-labels-idx1-ubyte.gz
Epoch: 0    - Cost: 12.5     Valid Accuracy: 0.0948
Epoch: 1    - Cost: 11.4     Valid Accuracy: 0.102
Epoch: 2    - Cost: 10.7     Valid Accuracy: 0.114
Epoch: 3    - Cost: 10.1     Valid Accuracy: 0.13 
Epoch: 4    - Cost: 9.7      Valid Accuracy: 0.146
Epoch: 5    - Cost: 9.36     Valid Accuracy: 0.162
Epoch: 6    - Cost: 9.04     Valid Accuracy: 0.18 
Epoch: 7    - Cost: 8.73     Valid Accuracy: 0.194
Epoch: 8    - Cost: 8.43     Valid Accuracy: 0.215
Epoch: 9    - Cost: 8.14     Valid Accuracy: 0.231
Epoch: 10   - Cost: 7.85     Valid Accuracy: 0.251
Epoch: 11   - Cost: 7.57     Valid Accuracy: 0.265
Epoch: 12   - Cost: 7.31     Valid Accuracy: 0.282
Epoch: 13   - Cost: 7.05     Valid Accuracy: 0.298
Epoch: 14   - Cost: 6.8      Valid Accuracy: 0.

In [4]:
import numpy as np
np.min([1, 2])

1

# 14. Quiz: TensorFlow ReLUs

In [7]:
# Solution is available in the other "solution.py" tab
import tensorflow as tf

output = None
hidden_layer_weights = [
    [0.1, 0.2, 0.4],
    [0.4, 0.6, 0.6],
    [0.5, 0.9, 0.1],
    [0.8, 0.2, 0.8]]
out_weights = [
    [0.1, 0.6],
    [0.2, 0.1],
    [0.7, 0.9]]

# Weights and biases
weights = [
    tf.Variable(hidden_layer_weights),
    tf.Variable(out_weights)]
biases = [
    tf.Variable(tf.zeros(3)),
    tf.Variable(tf.zeros(2))]

# Input
features = tf.Variable([[1.0, 2.0, 3.0, 4.0], [-1.0, -2.0, -3.0, -4.0], [11.0, 12.0, 13.0, 14.0]])

# TODO: Create Model
hidden_input = tf.add(tf.matmul(features, weights[0]), biases[0])
hidden_output = tf.nn.relu(hidden_input)

output_input = tf.add(tf.matmul(hidden_output, weights[1]), biases[1])
output_output = output_input


# TODO: Print session results
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    output_output_val = sess.run(output_output)
    print(output_output_val)


[[  5.11000013   8.44000053]
 [  0.           0.        ]
 [ 24.01000214  38.23999786]]


# 18. Quiz: TensorFlow Dropout

In [10]:
# Solution is available in the other "solution.py" tab
import tensorflow as tf

hidden_layer_weights = [
    [0.1, 0.2, 0.4],
    [0.4, 0.6, 0.6],
    [0.5, 0.9, 0.1],
    [0.8, 0.2, 0.8]]
out_weights = [
    [0.1, 0.6],
    [0.2, 0.1],
    [0.7, 0.9]]

# Weights and biases
weights = [
    tf.Variable(hidden_layer_weights),
    tf.Variable(out_weights)]
biases = [
    tf.Variable(tf.zeros(3)),
    tf.Variable(tf.zeros(2))]

# Input
features = tf.Variable([[0.0, 2.0, 3.0, 4.0], [0.1, 0.2, 0.3, 0.4], [11.0, 12.0, 13.0, 14.0]])

# TODO: Create Model with Dropout
keep_prob = tf.placeholder(tf.float32)

hidden_input = tf.add(tf.matmul(features, weights[0]), biases[0])
hidden_output = tf.nn.relu(hidden_input)
hidden_output = tf.nn.dropout(hidden_output, keep_prob)

output_input = tf.add(tf.matmul(hidden_output, weights[1]), biases[1])
output_output = output_input


# TODO: Print logits from a session
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    hidden_output_val, output_output_val = sess.run([hidden_output, output_output], feed_dict={keep_prob: 0.5})
    print('hidden_output_val\n', hidden_output_val)
    print('output_output_val\n', output_output_val)


hidden_output_val
 [[ 11.           9.39999962   0.        ]
 [  0.           0.           0.        ]
 [  0.          47.79999924   0.        ]]
output_output_val
 [[ 2.98000002  7.54000044]
 [ 0.          0.        ]
 [ 9.56000042  4.78000021]]


In [ ]:
# # keep_prob = 1.0
# hidden_output_val
#  [[  5.5          4.69999981   4.69999981]
#  [  0.56000006   0.49000004   0.51000005]
#  [ 23.59999847  23.89999962  24.10000038]]
# output_output_val
#  [[  4.77999973   8.        ]
#  [  0.51100004   0.8440001 ]
#  [ 24.01000214  38.23999786]]
    

# # keep_prob = 0.5
# hidden_output_val
#  [[ 11.           0.           9.39999962]
#  [  1.12000012   0.           1.0200001 ]
#  [ 47.19999695   0.           0.        ]]
# output_output_val
#  [[  7.67999935  15.05999947]
#  [  0.82600003   1.59000015]
#  [  4.71999979  28.31999969]]    
    

# # keep_prob = 0.5
# hidden_output_val
#  [[ 11.           9.39999962   9.39999962]
#  [  1.12000012   0.           0.        ]
#  [ 47.19999695  47.79999924   0.        ]]
# output_output_val
#  [[  9.55999947  16.        ]
#  [  0.11200001   0.67200011]
#  [ 14.28000069  33.09999847]]    