In [3]:
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.DataFrame({'A': ['a', 'b', 'a'], 'B': ['b', 'a', 'c'], 'C': [1, 2, 3]})
df

A  B  C
0  a  b  1
1  b  a  2
2  a  c  3

In [5]:
pd.get_dummies(df)

C  A_a  A_b  B_a  B_b  B_c
0  1    1    0    0    1    0
1  2    0    1    1    0    0
2  3    1    0    0    0    1

In [6]:
pd.get_dummies(df, columns=['A'])

B  C  A_a  A_b
0  b  1    1    0
1  a  2    0    1
2  c  3    1    0

In [7]:
df

A  B  C
0  a  b  1
1  b  a  2
2  a  c  3

In [14]:
df['C'] = df['C'] + 1

In [15]:
df

A  B  C
0  1  b  2
1  1  a  2
2  1  c  2

In [13]:
df.loc[:, 'C'] = 1
df

A  B  C
0  1  b  1
1  1  a  1
2  1  c  1

In [18]:
np.array([[1], [2], [3]]) * np.array([[4], [5], [6]])

array([[ 4],
       [10],
       [18]])

In [22]:
np.array([[1], [2], [3]]) * np.array([4, 5, 6])

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [25]:
np.dot(np.array([4, 5, 6]), np.array([[1], [2], [3]]))

array([32])

In [33]:
np.array([[1], [2], [3]]) * np.array([4, 5, 6])[:, None]

array([[ 4],
       [10],
       [18]])

In [34]:
np.array([1, 2, 3]) * np.array([4, 5, 6])

array([ 4, 10, 18])

In [36]:
np.array([1, 2, 3]) * np.array([4, 5, 6])[:, None]

array([[ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18]])

In [39]:
np.array([4, 5, 6])[:, None] * np.array([1, 2, 3])

array([[ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18]])

In [40]:
np.array([1]) * np.array([4, 5, 6])[:, None]

array([[4],
       [5],
       [6]])

In [28]:
np.array([1, 1]) * np.array([[3, 4], [5, 6], [7, 8]])

array([[3, 4],
       [5, 6],
       [7, 8]])

In [29]:
np.array([[3, 4], [5, 6], [7, 8]]) * np.array([1, 1])

array([[3, 4],
       [5, 6],
       [7, 8]])

In [31]:
np.dot(np.array([1, 1]), np.array([[3, 4], [5, 6], [7, 8]]))

ValueError: shapes (2,) and (3,2) not aligned: 2 (dim 0) != 3 (dim 0)

In [32]:
np.dot(np.array([[3, 4], [5, 6], [7, 8]]), np.array([1, 1]))

array([ 7, 11, 15])

In [41]:
np.dot(np.array([[3, 4], [5, 6], [7, 8]]), np.array([[1, 1], [2, 2]]))

array([[11, 11],
       [17, 17],
       [23, 23]])

In [42]:
np.dot(np.array([[3, 4]]), np.array([[1, 1], [2, 2]]))

array([[11, 11]])