# Lesson 4: Jupyter Notebooks

## Link
**Note**, here is the [Markdown syntax](https://daringfireball.net/projects/markdown/basics)

[Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)


## Code
Inline `import os` or `print('test')`

Block
```
import os
print('test')
``` 

    import os
    print('test')
    
    
## Math

Inline $y = mx + b$

Block
$$
y = mx + b
$$

# Magic Keywords

## Debug in Notebook

In [15]:
%pdb  # enter 'q' in prompt to exit

Incorrect argument. Use on/1, off/0, or nothing for a toggle.


In [16]:
def func(lst):
    a = 1    
    b = sum(lst)

func('abc')

TypeError: unsupported operand type(s) for +: 'int' and 'str'

> <ipython-input-16-64e58cc207d6>(3)func()
      1 def func(lst):
      2     a = 1
----> 3     b = sum(lst)
      4 
      5 func('abc')

ipdb> a
lst = 'abc'
ipdb> lst
'abc'
ipdb> a
lst = 'abc'
ipdb> b
ipdb> 1
1
ipdb> q


# Lesson 5: Matrix Math and NumPy Refresher

In [2]:
import numpy as np

In [44]:
s = np.array(1)
print(type(s), s.shape)
print(s + 5)
print(s.shape)

<class 'numpy.ndarray'> ()
6
()


In [5]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])
print(t)

[[[[ 1]
   [ 2]]

  [[ 3]
   [ 4]]

  [[ 5]
   [ 6]]]


 [[[ 7]
   [ 8]]

  [[ 9]
   [10]]

  [[11]
   [12]]]


 [[[13]
   [14]]

  [[15]
   [16]]

  [[17]
   [17]]]]


In [99]:
v = np.array([1,2,3,4])
print(type(v), v.shape, v)

<class 'numpy.ndarray'> (4,) [1 2 3 4]


In [50]:
v1 = v.reshape(1, 4)
print(type(v1), v1.shape, v1)

<class 'numpy.ndarray'> (1, 4) [[1 2 3 4]]


In [53]:
v2 = v.reshape(4, 1)
print(type(v2), v2.shape, v2)

<class 'numpy.ndarray'> (4, 1) [[1]
 [2]
 [3]
 [4]]


In [66]:
print(v[None])

[[1 2 3 4]]


In [21]:
print(v[None, :])

[[1 2 3 4]]


In [60]:
print(v[None, 0:2])

[[1 2]]


In [10]:
print(v[:, None])

[[1]
 [2]
 [3]
 [4]]


In [64]:
print(v[None, None])

[[[1 2 3 4]]]


In [63]:
print(v[None, None, 1:3])

[[[2 3]]]


In [30]:
y = np.array([[1,2,3,4], [5, 6, 7, 8]])
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
print(y[None, 0:1])

[[[1 2 3 4]]]


In [54]:
print(y[:, 0:1])

[[1]
 [5]]


In [68]:
v = np.array([1,2,3,4])

In [70]:
v1 = v
print(v1)

[1 2 3 4]


In [71]:
v1[0] = 5
print(v1)

[5 2 3 4]


In [72]:
print(v)

[5 2 3 4]


In [75]:
v ** 2

array([25,  4,  9, 16])

In [93]:
y = np.array([[1,2,3,4], [5, 6, 7, 8]])
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [96]:
yt = y.T
yt

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [89]:
yt = np.transpose(y)
yt

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [90]:
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [97]:
y[0][1] = -2
y

array([[ 1, -2,  3,  4],
       [ 5,  6,  7,  8]])

In [98]:
yt

array([[ 1,  5],
       [-2,  6],
       [ 3,  7],
       [ 4,  8]])

In [102]:
y / 2


array([[ 0.5, -1. ,  1.5,  2. ],
       [ 2.5,  3. ,  3.5,  4. ]])

## NumPy Quiz

In [103]:
# Use the numpy library
import numpy as np


def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = np.array(inputs)[None, :]
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    inputs_minus_min = input_array - np.min(input_array)

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    inputs_div_max = inputs_minus_min / np.max(inputs_minus_min)

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max
    

def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    m1_shape = m1.shape
    m2_shape = m2.shape
    
    if not ((m1_shape[1] == m2_shape[0]) or (m1_shape[0] == m2_shape[1])):
        return False
        

    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    if m1_shape[1] == m2_shape[0]:
        return np.matmul(m1, m2)
    else:
        return np.matmul(m2, m1)
    

def find_mean(values):
    # TODO: Return the average of the values in the given Python list
    return np.mean(np.array(values))


input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[ 0.     0.375  1.   ]]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
[[ 9 12 15]]
Mean == 2.6666666666666665
