In [9]:
# Solution is available in the other "sandbox_solution.py" tab
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
from quiz import get_weights, get_biases, linear


def mnist_features_labels(n_labels):
    """
    Gets the first <n> labels from the MNIST dataset
    :param n_labels: Number of labels to use
    :return: Tuple of feature list and label list
    """
    mnist_features = []
    mnist_labels = []

#     '/datasets/ud730/mnist'
    mnist = input_data.read_data_sets('/datasets/ud730/mnist', one_hot=True)

    # In order to make quizzes run faster, we're only looking at 10000 images
    for mnist_feature, mnist_label in zip(*mnist.train.next_batch(10000)):

        # Add features and labels if it's for the first <n>th labels
        if mnist_label[:n_labels].any():
            mnist_features.append(mnist_feature)
            mnist_labels.append(mnist_label[:n_labels])

    return mnist_features, mnist_labels


# Number of features (28*28 image is 784 features)
n_features = 784
# Number of labels
n_labels = 3

# Features and Labels
features = tf.placeholder(tf.float32)
labels = tf.placeholder(tf.float32)

# Weights and Biases
w = get_weights(n_features, n_labels)
b = get_biases(n_labels)

# Linear Function xW + b
logits = linear(features, w, b)

# Training data
train_features, train_labels = mnist_features_labels(n_labels)


with tf.Session() as session:
    # TODO: Initialize session variables
    init = tf.global_variables_initializer()
    session.run(init)
    
    # Softmax
    prediction = tf.nn.softmax(logits)

    # Cross entropy
    # This quantifies how far off the predictions were.
    # You'll learn more about this in future lessons.
    cross_entropy = -tf.reduce_sum(labels * tf.log(prediction), reduction_indices=1)

    # Training loss
    # You'll learn more about this in future lessons.
    loss = tf.reduce_mean(cross_entropy)

    # Rate at which the weights are changed
    # You'll learn more about this in future lessons.
    learning_rate = 0.08

    # Gradient Descent
    # This is the method used to train the model
    # You'll learn more about this in future lessons.
    optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss)

    # Run optimizer and get loss
    _, loss_val, w_val, b_val = session.run(
        [optimizer, loss, w, b],
        feed_dict={features: train_features, labels: train_labels})

# Print loss
print('loss_val: {}'.format(loss_val))
print('w_val: {}'.format(w_val))
print('b_val: {}'.format(b_val))


Extracting mnist/train-images-idx3-ubyte.gz
Extracting mnist/train-labels-idx1-ubyte.gz
Extracting mnist/t10k-images-idx3-ubyte.gz
Extracting mnist/t10k-labels-idx1-ubyte.gz
loss_val: 13.99600601196289
w_val: [[-0.7289508   1.24994183  0.04794432]
 [-0.20795234  0.04407349 -0.66270852]
 [-0.49697727 -0.7246536  -0.47702223]
 ..., 
 [ 0.57109684  1.4043566   0.07992199]
 [ 0.48272738  0.69664574  0.29628733]
 [-0.89415509  0.17725924 -0.45106769]]
b_val: [-0.04439961  0.02751592  0.0168831 ]


In [6]:
# Solution is available in the other "sandbox_solution.py" tab
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
from quiz import get_weights, get_biases, linear


# Weights and Biases
w = tf.constant([[1, 2, 3], [4, 5, 6]])
b = tf.constant([8, 9, 10])

# Linear Function xW + b
# logits = w + b
logits = tf.add(w, b)

init = tf.global_variables_initializer()

with tf.Session() as session:
    # TODO: Initialize session variables
    session.run(init)
    
    ll = session.run(logits)
    
# Print loss
print(ll)


[[ 9 11 13]
 [12 14 16]]


# 7. Quiz: TensorFlow Softmax

In [10]:
# Solution is available in the other "solution.py" tab
import tensorflow as tf


def run():
    output = None
    logit_data = [2.0, 1.0, 0.1]
    logits = tf.placeholder(tf.float32)
    
    # TODO: Calculate the softmax of the logits
    softmax = tf.nn.softmax(logits)
    
    with tf.Session() as sess:
        # TODO: Feed in the logit data
        output = sess.run(softmax, feed_dict={logits: logit_data})

    return output

run()

array([ 0.65900117,  0.24243298,  0.09856589], dtype=float32)

In [11]:
0.659 / 0.242, 0.242/0.0985

(2.723140495867769, 2.4568527918781724)

# 8. Quiz: TensorFlow Cross Entropy

In [24]:
# Solution is available in the other "solution.py" tab
import tensorflow as tf

softmax_data = [0.7, 0.2, 0.1]
one_hot_data = [1.0, 0.0, 0.0]

softmax = tf.placeholder(tf.float32)
one_hot = tf.placeholder(tf.float32)

tmp = one_hot * tf.log(softmax)

cross_entropy = -tf.reduce_sum(one_hot * tf.log(softmax))

# TODO: Print cross entropy from session
with tf.Session() as sess:    
    tmp_val, cross_entropy_val = sess.run([tmp, cross_entropy], feed_dict={
        softmax: softmax_data,
        one_hot: one_hot_data,
    })
    print(tmp_val)    
    print(cross_entropy_val)

[-0.35667497 -0.         -0.        ]
0.356675


## solution.py

In [25]:
# Quiz Solution
# Note: You can't run code in this tab
import tensorflow as tf

softmax_data = [0.7, 0.2, 0.1]
one_hot_data = [1.0, 0.0, 0.0]

softmax = tf.placeholder(tf.float32)
one_hot = tf.placeholder(tf.float32)

# ToDo: Print cross entropy from session
cross_entropy = -tf.reduce_sum(tf.multiply(one_hot, tf.log(softmax)))

with tf.Session() as sess:
    print(sess.run(cross_entropy, feed_dict={softmax: softmax_data, one_hot: one_hot_data}))


0.356675
