# 2. Quiz: Convolutional Layers

In [39]:
"""
Setup the strides, padding and filter weight/bias such that
the output shape is (1, 2, 2, 3).
"""
import tensorflow as tf
import numpy as np

# `tf.nn.conv2d` requires the input be 4D (batch_size, height, width, depth)
# (1, 4, 4, 1)
x = np.array([
    [0, 1, 0.5, 10],
    [2, 2.5, 1, -8],
    [4, 0, 5, 6],
    [15, 1, 2, 3]], dtype=np.float32).reshape((1, 4, 4, 1))
X = tf.constant(x)


def conv2d(input):
    # Filter (weights and bias)
    # The shape of the filter weight is (height, width, input_depth, output_depth)
    # The shape of the filter bias is (output_depth,)
    # TODO: Define the filter weights `F_W` and filter bias `F_b`.
    # NOTE: Remember to wrap them in `tf.Variable`, they are trainable parameters after all.
    F_W = tf.Variable(tf.truncated_normal([2, 2, 1, 3]))
    F_b = tf.Variable(tf.zeros(3))
    # TODO: Set the stride for each dimension (batch_size, height, width, depth)
    strides = [1, 2, 2, 1]
    # TODO: set the padding, either 'VALID' or 'SAME'.
    padding = 'SAME'
    # https://www.tensorflow.org/versions/r0.11/api_docs/python/nn.html#conv2d
    # `tf.nn.conv2d` does not include the bias computation so we have to add it ourselves after.
#     return tf.nn.conv2d(input, F_W, strides, padding) + F_b
    return tf.nn.bias_add(tf.nn.conv2d(input, F_W, strides, padding), F_b)

out = conv2d(X)

b_tmp = tf.constant([1.0, 2.0, 3.0])

# Lecture Note: The tf.nn.bias_add() function adds a 1-d bias to the last dimension in a matrix. (Note: using tf.add() doesn't work when the tensors aren't the same shape.)
# Rui test: all three works here
# out_tmp = out + b_tmp
# out_tmp = tf.add(out, b_tmp)
out_tmp = tf.nn.bias_add(out, b_tmp)

In [40]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    out_val, b_tmp_val, out_tmp_val = sess.run([out, b_tmp, out_tmp])
    print(out_val.shape)
    print(out_val)
    for i in range(3):
        print(out_val[0, :, :, i]) 
        
    print('b_tmp_val\n', b_tmp_val)
    print('out_tmp_val\n', out_tmp_val)        

(1, 2, 2, 3)
[[[[ -3.61456823  -5.82835484  -0.91199523]
   [  6.4423337   14.23735046   4.33617592]]

  [[  1.00528979 -19.34800911 -17.04005432]
   [ -1.41689062  -4.32622719  -4.27193022]]]]
[[-3.61456823  6.4423337 ]
 [ 1.00528979 -1.41689062]]
[[ -5.82835484  14.23735046]
 [-19.34800911  -4.32622719]]
[[ -0.91199523   4.33617592]
 [-17.04005432  -4.27193022]]
b_tmp_val
 [ 1.  2.  3.]
out_tmp_val
 [[[[ -2.61456823  -3.82835484   2.08800483]
   [  7.4423337   16.23735046   7.33617592]]

  [[  2.00528979 -17.34800911 -14.04005432]
   [ -0.41689062  -2.32622719  -1.27193022]]]]


In [24]:
"""
Setup the strides, padding and filter weight/bias such that
the output shape is (1, 2, 2, 3).
"""
import tensorflow as tf
import numpy as np

# `tf.nn.conv2d` requires the input be 4D (batch_size, height, width, depth)
# (1, 4, 4, 1)
x = np.array([
    [0, 1, 0.5, 10],
    [2, 2.5, 1, -8],
    [4, 0, 5, 6],
    [15, 1, 2, 3]], dtype=np.float32).reshape((1, 4, 4, 1))
X = tf.constant(x)


def conv2d(input):
    # Filter (weights and bias)
    # The shape of the filter weight is (height, width, input_depth, output_depth)
    # The shape of the filter bias is (output_depth,)
    # TODO: Define the filter weights `F_W` and filter bias `F_b`.
    # NOTE: Remember to wrap them in `tf.Variable`, they are trainable parameters after all.
    F_W = tf.Variable(tf.truncated_normal([3, 3, 1, 3]))
    F_b = tf.Variable(tf.zeros(3))
    # TODO: Set the stride for each dimension (batch_size, height, width, depth)
    strides = [1, 1, 1, 1]
    # TODO: set the padding, either 'VALID' or 'SAME'.
    padding = 'VALID'
    # https://www.tensorflow.org/versions/r0.11/api_docs/python/nn.html#conv2d
    # `tf.nn.conv2d` does not include the bias computation so we have to add it ourselves after.
    return tf.nn.conv2d(input, F_W, strides, padding) + F_b

out = conv2d(X)

In [25]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    out_val = sess.run(out)
    print(out_val.shape)
    print(out_val)
    for i in range(3):
        print(out_val[0, :, :, i])    

(1, 2, 2, 3)
[[[[ -8.94327641   9.03826332  -9.48495197]
   [-15.12922287   1.65697861  -6.69941425]]

  [[-13.37130928  29.46146202 -25.25383949]
   [ -8.12068176   6.2870245   -1.013906  ]]]]
[[ -8.94327641 -15.12922287]
 [-13.37130928  -8.12068176]]
[[  9.03826332   1.65697861]
 [ 29.46146202   6.2870245 ]]
[[ -9.48495197  -6.69941425]
 [-25.25383949  -1.013906  ]]


# 5. Quiz: Max Pooling Layers

In [41]:
"""
Set the values to `strides` and `ksize` such that
the output shape after pooling is (1, 2, 2, 1).
"""
import tensorflow as tf
import numpy as np

# `tf.nn.max_pool` requires the input be 4D (batch_size, height, width, depth)
# (1, 4, 4, 1)
x = np.array([
    [0, 1, 0.5, 10],
    [2, 2.5, 1, -8],
    [4, 0, 5, 6],
    [15, 1, 2, 3]], dtype=np.float32).reshape((1, 4, 4, 1))
X = tf.constant(x)

def maxpool(input):
    # TODO: Set the ksize (filter size) for each dimension (batch_size, height, width, depth)
    ksize = [1, 2, 2, 1]
    # TODO: Set the stride for each dimension (batch_size, height, width, depth)
    strides = [1, 2, 2, 1]
    # TODO: set the padding, either 'VALID' or 'SAME'.
    padding = 'SAME'
    # https://www.tensorflow.org/versions/r0.11/api_docs/python/nn.html#max_pool
    return tf.nn.max_pool(input, ksize, strides, padding)
    
out = maxpool(X)

In [42]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    out_val= sess.run(out)
    print(out_val.shape)

(1, 2, 2, 1)


# 7. CNNs in TensorFlow

In [43]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets(".", one_hot=True, reshape=False)

import tensorflow as tf

# parameters
learning_rate = 0.00001
epochs = 10
batch_size = 128

# number of samples to calculate validation and accuracy
# decrease this if you're running out of memory
test_valid_size = 256

# network Parameters
n_classes = 10  # MNIST total classes (0-9 digits)
dropout = 0.75  # dropout (probability to keep units)

Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting ./train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting ./train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting ./t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting ./t10k-labels-idx1-ubyte.gz


In [44]:
# store weights & biases
weights = {
    'wc1': tf.Variable(tf.random_normal([5, 5, 1, 32])),
    'wc2': tf.Variable(tf.random_normal([5, 5, 32, 64])),
    'wd1': tf.Variable(tf.random_normal([7*7*64, 1024])),
    'out': tf.Variable(tf.random_normal([1024, n_classes]))}

biases = {
    'bc1': tf.Variable(tf.random_normal([32])),
    'bc2': tf.Variable(tf.random_normal([64])),
    'bd1': tf.Variable(tf.random_normal([1024])),
    'out': tf.Variable(tf.random_normal([n_classes]))}

In [45]:
def conv2d(x, W, b, strides=1):
    x = tf.nn.conv2d(x, W, strides=[1, strides, strides, 1], padding='SAME')
    x = tf.nn.bias_add(x, b)
    return tf.nn.relu(x)

In [46]:
def maxpool2d(x, k=2):
    return tf.nn.max_pool(
        x,
        ksize=[1, k, k, 1],
        strides=[1, k, k, 1],
        padding='SAME')

In [47]:
def conv_net(x, weights, biases, dropout):
    # Layer 1 - 28*28*1 to 14*14*32
    conv1 = conv2d(x, weights['wc1'], biases['bc1'])
    conv1 = maxpool2d(conv1, k=2)

    # Layer 2 - 14*14*32 to 7*7*64
    conv2 = conv2d(conv1, weights['wc2'], biases['bc2'])
    conv2 = maxpool2d(conv2, k=2)

    # Fully connected layer - 7*7*64 to 1024
    fc1 = tf.reshape(conv2, [-1, weights['wd1'].get_shape().as_list()[0]])
    fc1 = tf.add(tf.matmul(fc1, weights['wd1']), biases['bd1'])
    fc1 = tf.nn.relu(fc1)
    fc1 = tf.nn.dropout(fc1, dropout)

    # Output Layer - class prediction - 1024 to 10
    out = tf.add(tf.matmul(fc1, weights['out']), biases['out'])
    return out

In [ ]:
# tf Graph input
x = tf.placeholder(tf.float32, [None, 28, 28, 1])
y = tf.placeholder(tf.float32, [None, n_classes])
keep_prob = tf.placeholder(tf.float32)

# Model
logits = conv_net(x, weights, biases, keep_prob)

# Define loss and optimizer
cost = tf.reduce_mean(\
    tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)\
    .minimize(cost)

# Accuracy
correct_pred = tf.equal(tf.argmax(logits, 1), tf.argmax(y, 1))
accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))

# Initializing the variables
init = tf. global_variables_initializer()

# Launch the graph
with tf.Session() as sess:
    sess.run(init)

    for epoch in range(epochs):
        for batch in range(mnist.train.num_examples//batch_size):
            batch_x, batch_y = mnist.train.next_batch(batch_size)
            sess.run(optimizer, feed_dict={
                x: batch_x,
                y: batch_y,
                keep_prob: dropout})

            # Calculate batch loss and accuracy
            loss = sess.run(cost, feed_dict={
                x: batch_x,
                y: batch_y,
                keep_prob: 1.})
            valid_acc = sess.run(accuracy, feed_dict={
                x: mnist.validation.images[:test_valid_size],
                y: mnist.validation.labels[:test_valid_size],
                keep_prob: 1.})

            print('Epoch {:>2}, Batch {:>3} -'
                  'Loss: {:>10.4f} Validation Accuracy: {:.6f}'.format(
                epoch + 1,
                batch + 1,
                loss,
                valid_acc))

    # Calculate Test Accuracy
    test_acc = sess.run(accuracy, feed_dict={
        x: mnist.test.images[:test_valid_size],
        y: mnist.test.labels[:test_valid_size],
        keep_prob: 1.})
    print('Testing Accuracy: {}'.format(test_acc))

Epoch  1, Batch   1 -Loss: 56891.6328 Validation Accuracy: 0.070312
Epoch  1, Batch   2 -Loss: 46594.3984 Validation Accuracy: 0.078125
Epoch  1, Batch   3 -Loss: 37274.9844 Validation Accuracy: 0.089844
Epoch  1, Batch   4 -Loss: 34622.7891 Validation Accuracy: 0.089844
Epoch  1, Batch   5 -Loss: 30409.2266 Validation Accuracy: 0.089844
Epoch  1, Batch   6 -Loss: 27175.3965 Validation Accuracy: 0.109375
Epoch  1, Batch   7 -Loss: 23384.9805 Validation Accuracy: 0.113281
Epoch  1, Batch   8 -Loss: 25059.6426 Validation Accuracy: 0.128906
Epoch  1, Batch   9 -Loss: 24200.0312 Validation Accuracy: 0.152344
Epoch  1, Batch  10 -Loss: 20925.2480 Validation Accuracy: 0.144531
Epoch  1, Batch  11 -Loss: 20335.0078 Validation Accuracy: 0.167969
Epoch  1, Batch  12 -Loss: 22964.1738 Validation Accuracy: 0.171875
Epoch  1, Batch  13 -Loss: 20590.6973 Validation Accuracy: 0.167969
Epoch  1, Batch  14 -Loss: 18382.9648 Validation Accuracy: 0.175781
Epoch  1, Batch  15 -Loss: 17838.3398 Validation

Epoch  1, Batch 122 -Loss:  3817.3621 Validation Accuracy: 0.589844
Epoch  1, Batch 123 -Loss:  3842.1741 Validation Accuracy: 0.585938
Epoch  1, Batch 124 -Loss:  3129.9062 Validation Accuracy: 0.597656
Epoch  1, Batch 125 -Loss:  3934.8916 Validation Accuracy: 0.597656
Epoch  1, Batch 126 -Loss:  3225.8979 Validation Accuracy: 0.605469
Epoch  1, Batch 127 -Loss:  3820.1223 Validation Accuracy: 0.589844
Epoch  1, Batch 128 -Loss:  3191.0347 Validation Accuracy: 0.609375
Epoch  1, Batch 129 -Loss:  4429.4180 Validation Accuracy: 0.613281
Epoch  1, Batch 130 -Loss:  3583.1167 Validation Accuracy: 0.617188
Epoch  1, Batch 131 -Loss:  3718.4319 Validation Accuracy: 0.625000
Epoch  1, Batch 132 -Loss:  3728.9287 Validation Accuracy: 0.617188
Epoch  1, Batch 133 -Loss:  3733.8628 Validation Accuracy: 0.617188
Epoch  1, Batch 134 -Loss:  3523.2690 Validation Accuracy: 0.625000
Epoch  1, Batch 135 -Loss:  2017.6597 Validation Accuracy: 0.625000
Epoch  1, Batch 136 -Loss:  3874.8965 Validation

Epoch  1, Batch 243 -Loss:  2221.7991 Validation Accuracy: 0.691406
Epoch  1, Batch 244 -Loss:  1799.3040 Validation Accuracy: 0.695312
Epoch  1, Batch 245 -Loss:  2014.8044 Validation Accuracy: 0.699219
Epoch  1, Batch 246 -Loss:  2317.6743 Validation Accuracy: 0.703125
Epoch  1, Batch 247 -Loss:  2491.1558 Validation Accuracy: 0.703125
Epoch  1, Batch 248 -Loss:  1423.5707 Validation Accuracy: 0.695312
Epoch  1, Batch 249 -Loss:  2221.0195 Validation Accuracy: 0.699219
Epoch  1, Batch 250 -Loss:  2872.6406 Validation Accuracy: 0.687500
Epoch  1, Batch 251 -Loss:  1630.3405 Validation Accuracy: 0.691406
Epoch  1, Batch 252 -Loss:  1577.6605 Validation Accuracy: 0.695312
Epoch  1, Batch 253 -Loss:  1816.7122 Validation Accuracy: 0.699219
Epoch  1, Batch 254 -Loss:  1828.1387 Validation Accuracy: 0.699219
Epoch  1, Batch 255 -Loss:  1517.9529 Validation Accuracy: 0.691406
Epoch  1, Batch 256 -Loss:  2303.6494 Validation Accuracy: 0.687500
Epoch  1, Batch 257 -Loss:  2116.2275 Validation